version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
    ports:
      - 3008:3000
    command: "yarn start -H 0.0.0.0"
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - './api:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - FLASK_CONFIG=development
      - FLASK_ENV=development

  nginx:
    image: nginx:stable
    ports:
      - 8080:8080  # http://0.0.0.0:8080/ in the browser
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend

